### ISSUE TITLE
Overall submission of polls

### ISSUE THREAD

**Issue by mukulu** [chingalo/chingalo-first-app#1]
Make all polls get submitted in one go!!! Not individually.

**Comment by mukulu** [comment]
What happened to this one??? @chingalo  I see the vote button but no voting that happens,
And I can add new poll but i can't add answers along with that poll!!!

Make sure you finish that today, tomorrow we're moving forward.

**Comment by chingalo** [comment]
now  voting button work successful if and only if all polls have been selected..... but still trying to working on it.....

**Comment by chingalo** [comment]
try to check out

**Comment by chingalo** [comment]
only remain is lit bit customization of pages...  all function works successful....
